### PR TITLE
psplash: fix for distro other than "dey" #2

### PR DESCRIPTION
**Pull request by skladd**
see #11

ERROR: psplash-0.1+gitAUTOINC+44afb7506d-r0 do_fetch: Fetcher failure: Unable to find file file://logo.png;outsuffix=default anywhere.

### CODE REVIEW

**Comment by hpalacio** [comment]
Hi Stephan,

Although I agree with the change, I would like to understand how this fails in your case. Even if you are not using "dey" distro, what you report is a fetcher failure for the logo.png. This file is part of meta-digi-dey layer where this bbappend is so I don't quite understand that Yocto parses this recipe but at the same time cannot find the file which is in the files/ directory of this recipe.
Can you maybe share your conf/local.conf and bblayers.conf?
Thanks

**Comment by skladd** [comment]
Hi Héctor,

I think the fetcher does not find the file, because the digi directory `"${THISDIR}/files"` is added only if distro dey is used (at line 3).

It works also, if I remove the :dey suffix (and leave line 14 unchanged):
`FILESEXTRAPATHS:prepend := "${THISDIR}/files:"`
I guess the digi logo is used then also for other distros.

If you still want my configuration, I will share it.

**Comment by hpalacio** [comment]
Oh, yes, you're right. Thanks

**Comment by hpalacio** [comment]
Fixed in https://github.com/digi-embedded/meta-digi/commit/dd546d6f0629d79f9847c7ba615467957e394c05
Thanks!

**Pull request closed without merging**
