### PR TITLE
meta-digi-dey: swupdate: enable openssl in defconfig

### PR DESCRIPTION
**Pull request by skladd**
The removed line `CONFIG_SSL_IMPL_OPENSSL=y` obviously causes the build of swupdate to fail if INIT_MANAGER is set to `sysvinit` (e.g. to build `dey-image-tiny`).
By (re-)enabling CONFIG_SSL_IMPL_OPENSSL openssl is added as build dependency to swupdate, avoiding `fatal error: openssl/bio.h: No such file or directory`.

### CODE REVIEW

**Comment by digiinternational** [comment]
Hello @skladd,

This line was removed from meta-digi's swupdate defconfig on a cleanup done in commit 429125cce02ac28c7b64e460a92d7fcb5aade7a8.
The line was automatically removed because `CONFIG_SSL_IMPL_OPENSSL` is enabled by default on meta-swupdate Kconfig.

Having said that, I tried to build `dey-image-tiny` for one of our platforms (ccmp15-dvk) previously setting `INIT_MANAGER = "sysvinit"` and I could not reproduce the issue. swupdate builds fine; its `.config` file defines `CONFIG_SSL_IMPL_OPENSSL=y` and openssl is built as well.

Regards,
Héctor Palacios

**Comment by skladd** [comment]
Hello Héctor,

I can confirm the build for the machine ccmp15-dvk passes. Could you try the machine "ccimx6sbc" (via `cc8x-cc6-beta.xml`), please? This one fails here, perhaps because of using different layers.

Thanks,
Stephan

**Comment by digiinternational** [comment]
Hello @skladd 

I can reproduce the issue when using ccimx6sbc platform. 
I found the root cause of the issue on that commit I referenced before (429125cce02ac28c7b64e460a92d7fcb5aade7a8). A python function in meta-swupdate is adding dependecies basing on config switches parsed from `defconfig` file and any other configuration fragment. For this reason, this `defconfig` file cannot be a minimal contents one. It has to be a full defconfig.
I will do a fix and post a PR soon.

Thanks for reporting!

Héctor Palacios

**Comment by digiinternational** [comment]
Hello @skladd,

We're in the middle of a release process so it may take some days for us to merge this fix.
For reference, find it attached until it goes public.

[0001-swupdate-restore-a-full-defconfig-out-of-a-.config.zip](https://github.com/digi-embedded/meta-digi/files/12607727/0001-swupdate-restore-a-full-defconfig-out-of-a-.config.zip)

I will close this PR.
Héctor Palacios

**Pull request closed without merging**
